### ISSUE TITLE
What EuroC dataset did you use? 

### ISSUE THREAD

**Issue by tn0432** [mbrossar/FUSION2018#1]
Hello! Thank you very much for sharing your code with the robotic community!
Just want to check what EuroC dataset did you use? I check on the website, they only have V2_02_medium and V2_01_easy. I can not find out the V2_01_medium. 

Thanks

**Comment by mbrossar** [comment]
Hello,

I used both the dataset V2_02_medium and V2_01_easy and the paper shows 
the results only for the V2_02_medium case.


Le 04/12/2017 à 22:18, Trung Nguyen a écrit :

**Comment by tn0432** [comment]
Hello! Thank you for your reply!
I am trying to use V2_02_medium. I download the images and run the code. The error says that:
 "File "D:/database/V2_02_medium/mav0/cam0/data/1403715529362143000.png" does not exist"
So, I try to locate the image file 1403715529362143000.png. And it does not exist in the dataset. I think the image name 1403715529362143000 has been round up! 
Any recommendations to fix the issue?

Thanks

**Comment by mbrossar** [comment]
When reading reading an image, the code searches a file 
"directory + indice_number_of_image + .png"
where it converts the indice_number_of_image from int to string.

This number is big (1403715523912143104 for exemple). Can you see what is the answers of 
`fprintf('%d\n',fileImages(1))`
after running the first line of the code. I do not have this problem on my computer and I have the feeling that your computer conserves only the first 15 digits.

If the problem persits, let me know and I will update the code.

**Comment by tn0432** [comment]
Hi!
I change the code image = strcat(dirImage,int2str(fileImages(IdxImage)),'.png');
 to image` = strcat(dirImage,sprintf( '%.10d', fileImages(IdxImage) `),'.png');
And it works.  Maybe, different Matlab version or configuration make the issue.
Thanks

**Comment by LeiZhang631** [comment]
Dear Dr. Martin Brossard，
I am very interested in this research work. However your paper pdf link is failed on the github. Could  you send me a copy of your paper ? Thank you very much.  Email: zhangleiactri@163.com

**Comment by mbrossar** [comment]
Hello Lei,

Thanks you for the remark, the link is now correct. Please also find the 
paper.

Best

Martin


Le 15/01/2018 à 14:12, LeiZhang631 a écrit :

**Comment by ouyangandy** [comment]
> When reading reading an image, the code searches a file
> "directory + indice_number_of_image + .png"
> where it converts the indice_number_of_image from int to string.
> 
> This number is big (1403715523912143104 for example). Can you see what is the answers of
> `fprintf('%d\n',fileImages(1))`
> after running the first line of the code. I do not have this problem on my computer and I have the feeling that your computer conserves only the first 15 digits.
> 
> If the problem persits, let me know and I will update the code.

still not resolve this problem, could you help me ,  I change the code image = strcat(dirImage,int2str(fileImages(IdxImage)),'.png');
to image= strcat(dirImage,sprintf( '%.10d', fileImages(IdxImage)),'.png'), in managerAmers.m , like what u said , but not woked.
